title: Maestro
description: Portal Maestro
lang: pt-BR

url: "https://artursn002.github.io"
baseurl: "/System_Maestro"

encoding: utf-8
markdown: kramdown
safe: true

exclude:
  - Gemfile
  - Gemfile.lock
  - gemfile
  - gemfile.lock
  - output/
  - _site/
  - .jekyll-cache/
  - .sass-cache/
  - .bundle/
  - vendor/
  - .playwright-cli/
  - docs/
  - README.md
  - node_modules/
  - package.json
  - package-lock.json
  - playwright.config.js
  - playwright-report/
  - test-results/
  - tests/
  - "*.log"
